- hosts: localhost
  become_user: root
  become_method: su
  roles:
    - apt
    - nano
    - bashrc
    - htop
    - cmake
    - make
    - build-essential
    - pkg-config
    - libssl-dev
    - libboost-all-dev
    - bison
    - flex
    - default-libmysqlclient-dev
    - libpq-dev
    - libyajl-dev
    - libedit-dev
    - git
