- name: configure apt sources
  template:
    dest: /etc/apt/sources.list
    src: sources.list.j2
  become: true

- name: configure nano
  template:
    dest: /etc/nanorc
    src: nanorc.j2
  become: true

- name: enable bash auto completion
  template:
    dest: /etc/bash.bashrc
    src: bash.bashrc.j2
  become: true

- name: install htop
  apt:
    name: htop
    update_cache: yes
  become: true
