- name: apt present mariadb-server
  apt:
    name: mariadb-server
    state: present
    update_cache: yes
  become: true
  register: mysql_server_install

- name: apt present mariadb-client
  apt:
    name: mariadb-client
    state: present
    update_cache: yes
  become: true

- name: apt present python-mysqldb
  apt:
    name: python-mysqldb
    state: present
    update_cache: yes
  become: true

- name: mysql_user present root
  mysql_user: 
    name: root
    password: "{{ mysql_root_password }}"
    state: present
    login_user: "{{ mysql_root_username }}"
  become: true
  when: mysql_server_install.changed
