- name: apt present php5-fpm
  apt:
    name: php5-fpm
    state: present
    update_cache: yes
  become: true

- name: apt present php5-mysql
  apt: 
    name: php5-mysql
    state: present
    update_cache: yes
  become: true

- name: apt present php5-gd
  apt:
    name: php5-gd
    state: present
    update_cache: yes
  become: true

- name: apt present php5-intl
  apt:
    name: php5-intl
    state: present
    update_cache: yes
  become: true

- name: apt present php5-curl
  apt:
    name: php5-curl
    state: present
    update_cache: yes
  become: true

- name: apt present php5-imagick
  apt:
    name: php5-imagick
    state: present
    update_cache: yes
  become: true
